version: '3'


services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017
    volumes:
      - ./config/db:/data/db
    networks:
      - prod_network
    logging:
      options:
        max-size: 10m
        max-file: "3"
  backend:
    restart: always
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    env_file:
      - ./.prod.env
    expose:
      - 5000
    networks:
      - prod_network
    depends_on:
      - database
    logging:
      options:
        max-size: 10m
  nginx_server:
    build:
      context: nginx/
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prod_network


networks:
  prod_network:
    driver: bridge