version: '3'


services:

  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - ./config/db:/data/db
    networks:
      - prod_network
    logging:
      options:
        max-size: 10m
        max-file: "3"

  main_api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .prod.env
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - prod_network
    depends_on:
      - database
    logging:
      options:
        max-size: 10m


networks:
  prod_network:
    driver: bridge