version: '3'


services:

  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - ./config/db:/data/db
    networks:
      - prod_network
    logging:
      options:
        max-size: 10m
        max-file: "3"

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: uvicorn main:app --port 5000
    env_file:
      - .prod.env
    ports:
      - "83:5000"
    expose:
      - 83
    networks:
      - prod_network
    depends_on:
      - database
    logging:
      options:
        max-size: 10m


networks:
  prod_network:
    driver: bridge